-- Script to add test data
-- Test user: orga1@event.com / password123 (hashed)
-- Test user: client1@event.com / password123 (hashed)

-- Hash value for "password123" using PBKDF2 algorithm
-- The actual hash would be generated by PasswordUtils.hashPassword()
-- For now, using a default test hash

INSERT INTO personne (id, nom, prenom, email, telephone, mot_de_passe, role, actif, date_inscription, dtype)
VALUES (1, 'Dupont', 'Jean', 'orga1@event.com', '+33612345678', 
        '$2y$10$N3/OBGlPypgFM8C6MkAv0OlFJfVCbP4c4FJ4tCVwDhRyp7N3A7RBe', -- password123
        'ORGANISATEUR', true, NOW(), 'Organisateur');

INSERT INTO organisateur (id, type_organisation)
VALUES (1, 'PHYSIQUE');

INSERT INTO personne (id, nom, prenom, email, telephone, mot_de_passe, role, actif, date_inscription, dtype)
VALUES (2, 'Dubois', 'Marie', 'client1@event.com', '+33612345679',
        '$2y$10$N3/OBGlPypgFM8C6MkAv0OlFJfVCbP4c4FJ4tCVwDhRyp7N3A7RBe', -- password123
        'CLIENT', true, NOW(), 'Client');

INSERT INTO client (id)
VALUES (2);

-- Commit transaction
COMMIT;
